/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibPeerDASKZG */

#ifndef _Included_LibPeerDASKZG
#define _Included_LibPeerDASKZG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibPeerDASKZG
 * Method:    proverContextNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_LibPeerDASKZG_proverContextNew
  (JNIEnv *, jclass);

/*
 * Class:     LibPeerDASKZG
 * Method:    proverContextDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LibPeerDASKZG_proverContextDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     LibPeerDASKZG
 * Method:    computeCells
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LibPeerDASKZG_computeCells
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     LibPeerDASKZG
 * Method:    computeCellsAndKZGProofs
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LibPeerDASKZG_computeCellsAndKZGProofs
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     LibPeerDASKZG
 * Method:    blobToKZGCommitment
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LibPeerDASKZG_blobToKZGCommitment
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     LibPeerDASKZG
 * Method:    verifierContextNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_LibPeerDASKZG_verifierContextNew
  (JNIEnv *, jclass);

/*
 * Class:     LibPeerDASKZG
 * Method:    verifierContextDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_LibPeerDASKZG_verifierContextDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     LibPeerDASKZG
 * Method:    verifyCellKZGProof
 * Signature: (J[BJ[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_LibPeerDASKZG_verifyCellKZGProof
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
