/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ethereum_cryptography_LibPeerDASKZG */

#ifndef _Included_ethereum_cryptography_LibPeerDASKZG
#define _Included_ethereum_cryptography_LibPeerDASKZG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ethereum_cryptography_LibPeerDASKZG
 * Method:    peerDASContextNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ethereum_cryptography_LibPeerDASKZG_peerDASContextNew
  (JNIEnv *, jclass);

/*
 * Class:     ethereum_cryptography_LibPeerDASKZG
 * Method:    peerDASContextDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ethereum_cryptography_LibPeerDASKZG_peerDASContextDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ethereum_cryptography_LibPeerDASKZG
 * Method:    computeCells
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ethereum_cryptography_LibPeerDASKZG_computeCells
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ethereum_cryptography_LibPeerDASKZG
 * Method:    computeCellsAndKZGProofs
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ethereum_cryptography_LibPeerDASKZG_computeCellsAndKZGProofs
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ethereum_cryptography_LibPeerDASKZG
 * Method:    blobToKZGCommitment
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ethereum_cryptography_LibPeerDASKZG_blobToKZGCommitment
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     ethereum_cryptography_LibPeerDASKZG
 * Method:    verifyCellKZGProof
 * Signature: (J[BJ[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_ethereum_cryptography_LibPeerDASKZG_verifyCellKZGProof
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
