# WARNING: This file has been automatically generated by nbindgen. Do not edit by hand.


const NUM_BYTES_PROOFS* = 6144

const NUM_BYTES_CELLS* = 262144


type ProverContext* {.incompleteStruct.} = object

type VerifierContext* {.incompleteStruct.} = object

proc prover_context_new*(): ptr ProverContext {.importc: "prover_context_new".}

proc prover_context_free*(ctx: ptr ProverContext): void {.importc: "prover_context_free".}

proc blob_to_kzg_commitment*(ctx: ptr ProverContext,
                             blob: pointer,
                             outx: pointer): void {.importc: "blob_to_kzg_commitment".}

proc compute_cells_and_kzg_proofs*(ctx: ptr ProverContext,
                                   blob: pointer,
                                   out_cells: pointer,
                                   out_proofs: pointer): void {.importc: "compute_cells_and_kzg_proofs".}

proc verifier_context_new*(): ptr VerifierContext {.importc: "verifier_context_new".}

proc verifier_context_free*(ctx: ptr VerifierContext): void {.importc: "verifier_context_free".}
