/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ProverContextJs {
  constructor()
  blobToKzgCommitment(blob: Uint8Array): Uint8Array
}
export class VerifierContextJs { }
