name: Rust Package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      ref:
        description: "The reference (branch/tag/commit) to checkout "
        required: false
      release-type:
        type: choice
        required: false
        default: "none"
        description: "Indicates whether we want to make a release and if which one"
        options:
          - release
          - none

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'workflow_dispatch' && 'manual' || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: linux-arm64
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-pc-windows-gnu
            os: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86.0
          target: ${{ matrix.target }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.0.0"

      - name: Install libnode
        if: matrix.os == 'windows-latest'
        run: .github/scripts/install_libnode_dll_windows.sh
        shell: bash

      - name: Build
        run: RUST_BACKTRACE=full cargo build --target ${{ matrix.target }} --verbose
        shell: bash

      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --target ${{ matrix.target }}
        shell: bash

  cargo-clippy:
    runs-on: ubuntu-latest
    name: Clippy check

    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - name: Clippy Check
        run: cargo clippy --workspace --lib --examples --tests --benches --all-features --locked

  # We really only want to publish the eip7594 crate
  # However, crates.io forces us to publish its dependencies too.
  publish:
    name: Publish in order
    needs: build-and-test
    if: ${{ inputs.release-type != 'none' && github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.86.0

      # These steps are in a specific order so crate dependencies are updated first
      - name: Publish maybe_rayon
        run: cargo publish --package crate_crypto_internal_eth_kzg_maybe_rayon
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_RELEASE_TOKEN }}

      - name: Publish bls12_381
        run: cargo publish --package crate_crypto_internal_eth_kzg_bls12_381
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_RELEASE_TOKEN }}

      - name: Publish polynomial
        run: cargo publish --package crate_crypto_internal_eth_kzg_polynomial
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_RELEASE_TOKEN }}

      - name: Publish erasure_codes
        run: cargo publish --package crate_crypto_internal_eth_kzg_erasure_codes
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_RELEASE_TOKEN }}

      - name: Publish kzg_multi_open
        run: cargo publish --package crate_crypto_kzg_multi_open_fk20
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_RELEASE_TOKEN }}

      - name: Publish rust_eth_kzg
        run: cargo publish --package rust_eth_kzg
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_RELEASE_TOKEN }}
