name: Nim bindings

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.0.0'

      - name: Install libnode
        if: matrix.os == 'windows-latest'
        run: .github/scripts/install_libnode_dll_windows.sh
        shell: bash

      - name: Run compile script
        run: ./scripts/compile.sh nim
        shell: bash

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          nim-version: 'stable'
      
      - name: Install Nimble dependencies
        working-directory: bindings/nim/nim_code
        run: nimble install -Y

      - name: Test Nim project
        working-directory: bindings/nim/nim_code
        run: nimble test -Y
