name: Test Go bindings

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.0.0'

      - name: Install libnode
        if: matrix.os == 'windows-latest'
        run: .github/scripts/install_libnode_dll_windows.sh
        shell: bash

      - name: Run compile script
        run: ./scripts/compile.sh golang
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run Go tests
        run: go test ./...
        working-directory: bindings/golang
